feat: added options: unshare-appdirs, unshare-journal, privileged (unprivileged container by default), unconfined and escape-selinux

diff --git a/distrobox-isolated-create b/distrobox-isolated-create
--- a/distrobox-isolated-create
+++ b/distrobox-isolated-create
@@ -89,22 +89,34 @@ unshare_process=0
 unshare_devsys=0
 unshare_home=0
 unshare_root=0
+unshare_appdirs=0
+unshare_journal=0
 home_overlay_opts="-"
+privileged=0
+unconfined=0
+escape_selinux=0
 
 # Use cd + dirname + pwd so that we do not have relative paths in mount points
 # We're not using "realpath" here so that symlinks are not resolved this way
 # "realpath" would break situations like Nix or similar symlink based package
 # management.
-distrobox_entrypoint_path="$(cd "$(dirname "${0}")" && pwd)/distrobox-init"
+distrobox_entrypoint_path="$(cd "$(dirname "${0}")" && pwd)/distrobox-isolated-init"
 distrobox_export_path="$(cd "$(dirname "${0}")" && pwd)/distrobox-export"
 distrobox_genentry_path="$(cd "$(dirname "${0}")" && pwd)/distrobox-generate-entry"
 distrobox_hostexec_path="$(cd "$(dirname "${0}")" && pwd)/distrobox-host-exec"
 # In case some of the scripts are not in the same path as create, let's search
 # in PATH for them.
-[ ! -e "${distrobox_entrypoint_path}" ] && distrobox_entrypoint_path="$(command -v distrobox-init)"
+[ ! -e "${distrobox_entrypoint_path}" ] && distrobox_entrypoint_path="$(command -v distrobox-isolated-init)"
 [ ! -e "${distrobox_export_path}" ] && distrobox_export_path="$(command -v distrobox-export)"
 [ ! -e "${distrobox_genentry_path}" ] && distrobox_genentry_path="$(command -v distrobox-generate-entry)"
 [ ! -e "${distrobox_hostexec_path}" ] && distrobox_hostexec_path="$(command -v distrobox-host-exec)"
+# Resolve paths to real files if they are symlinks
+[ -L "${distrobox_entrypoint_path}" ] && distrobox_entrypoint_path="$(realpath "${distrobox_entrypoint_path}")"
+[ -L "${distrobox_export_path}" ] && distrobox_export_path="$(realpath "${distrobox_export_path}")"
+[ -L "${distrobox_genentry_path}" ] && distrobox_genentry_path="$(realpath "${distrobox_genentry_path}")"
+[ -L "${distrobox_hostexec_path}" ] && distrobox_hostexec_path="$(realpath "${distrobox_hostexec_path}")"
+
+
 # If the user runs this script as root in a login shell, set rootful=1.
 # There's no need for them to pass the --root flag option in such cases.
 [ "${container_user_uid}" -eq 0 ] && rootful=1 || rootful=0
@@ -231,10 +243,14 @@ Options:
 	--unshare-process:          do not share process namespace with host
 	--unshare-home:		do not share host home
 	--unshare-root:		do not share host root
+	--unshare-appdirs:  dot not share host ~/.local/share/{icons,applications}
 	--unshare-all:          activate all the unshare flags below
 	--overlay-home:		overlay host home (incompatible with with --unshare-home)
 				usage: --overlay-home <options>
 				where options are overlayfs options like "upperdir=<absolute path on host>,workdir=<absolute path on host>"
+	--privileged:		run container with ALL Linux kernel capabilities (dangerous)
+	--unconfined:       run container with apparmor=unconfined (without it gui doesn't work)
+	--escape-selinux:   run container with label=disable (selinux)
 	--compatibility/-C:	show list of compatible images
 	--help/-h:		show this message
 	--no-entry:		do not generate a container entry in the application list
@@ -327,6 +343,18 @@ while :; do
 			unshare_groups=1
 			unshare_process=1
 			;;
+		--privileged)
+			shift
+			privileged=1
+			;;
+		--unconfined)
+			shift
+			unconfined=1
+			;;
+		--escape-selinux)
+		    shift
+			escape_selinux=1
+			;;
 		--unshare-ipc)
 			shift
 			unshare_ipc=1
@@ -355,6 +383,14 @@ while :; do
 			shift
 			unshare_root=1
 			;;
+		--unshare-appdirs)
+			shift
+			unshare_appdirs=1
+			;;
+		--unshare-journal)
+			shift
+			unshare_journal=1
+			;;
 		--unshare-all)
 			shift
 			unshare_devsys=1
@@ -364,6 +400,8 @@ while :; do
 			unshare_process=1
 			unshare_home=1
 			unshare_root=1
+			unshare_appdirs=1
+			unshare_journal=1
 			;;
 		--overlay-home)
 			if [ -n "$2" ] && echo "$2" | grep -Eq "(workdir|upperdir)" ; then
@@ -610,7 +648,7 @@ fi
 # Check that we have a complete distrobox installation or
 # entrypoint and export will not work.
 if [ -z "${distrobox_entrypoint_path}" ] || [ -z "${distrobox_export_path}" ]; then
-	printf >&2 "Error: no distrobox-init found in %s\n" "${PATH}"
+	printf >&2 "Error: no distrobox-isolated-init found in %s\n" "${PATH}"
 	exit 127
 fi
 
@@ -690,7 +728,12 @@ get_clone_image()
 #   unshare_process: bool unshare proc
 #   unshare_home: bool unshare host's user home
 #   unshare_root: bool unshare host's root
+#   unshare_appdirs: bool unshare host's ~/.local/share/{icons,applications}
+#   unshare_journal: bool unshare host's /var/log/journal
 #   home_overlay_opts: string home overlay options
+#   privileged: bool run as a privileged container
+#   escape_selinux: bool run with label=disable
+#   unconfined: bool run apparmor=unconfined
 #
 # Expected env variables:
 #   None
@@ -705,11 +748,25 @@ generate_create_command()
 	result_command="${result_command}
 		--hostname \"${container_hostname}\"
 		--name \"${container_name}\"
-		--privileged
-		--security-opt label=disable
-		--security-opt apparmor=unconfined
+		--security-opt no-new-privileges
 		--pids-limit=-1
 		--user root:root"
+
+	if [ "${privileged}" -eq 1 ]; then
+		result_command="${result_command}
+		    --env PRIVILEGED=1
+			--privileged"
+	fi
+
+	if [ "${unconfined}" -eq 1 ]; then
+		result_command="${result_command}
+			--security-opt apparmor=unconfined"
+	fi
+
+	if [ "${escape_selinux}" -eq 1 ]; then
+		result_command="${result_command}
+			--security-opt label=disable"
+	fi
 
 	if [ "${unshare_ipc}" -eq 0 ]; then
 		result_command="${result_command}
@@ -740,7 +797,7 @@ generate_create_command()
 
 	if [ -z "${container_user_custom_home}" ] && [ "${unshare_home}" -eq 0 ] && [ "${home_overlay_opts}" != "-" ]; then
 		result_command="${result_command}
-			--env \"HOME=${container_user_home}\"
+			--env \"HOME=${container_use+ printf '\033[31m Error: could not start entrypoint.\n\033[0m'r_home}\"
 			--volume \"${container_user_home}\":\"${container_user_home}\":\"O${home_overlay_opts}\""
 	fi
 
@@ -752,7 +809,7 @@ generate_create_command()
 	# Mount user home, dev and host's root inside container.
 	# This grants access to external devices like usb webcams, disks and so on.
 	#
-	# Mount also the distrobox-init utility as the container entrypoint.
+	# Mount also the distrobox-isolated-init utility as the container entrypoint.
 	# Also mount in the container the distrobox-export and distrobox-host-exec
 	# utilities.
 	result_command="${result_command}
@@ -762,7 +819,7 @@ generate_create_command()
 		--env \"container=${container_manager}\"
 		--env \"TERMINFO_DIRS=/usr/share/terminfo:/run/host/usr/share/terminfo\"
 		--env \"CONTAINER_ID=${container_name}\"
-		--volume /tmp:/tmp:rslave
+		--mount type=tmpfs,destination=/tmp
 		--volume \"${distrobox_entrypoint_path}\":/usr/bin/entrypoint:ro
 		--volume \"${distrobox_export_path}\":/usr/bin/distrobox-export:ro
 		--volume \"${distrobox_hostexec_path}\":/usr/bin/distrobox-host-exec:ro"
@@ -800,7 +857,7 @@ generate_create_command()
 				--volume /:/run/host/:rslave"
 
 		fi
-	else
+	elif [ "${unshare_appdirs}" -eq 0 ]; then
 		# Only mount distrobox-export required paths:
 		# - needed icons in /run/host/$host_home/.local/share/icons
 		# - needed desktop files in /run/host/$host_home/.local/share/applications
@@ -865,7 +922,7 @@ generate_create_command()
 	#
 	# Ref. Podman issue 4452:
 	#    https://github.com/containers/podman/issues/4452
-	if [ -e "/sys/fs/selinux" ]; then
+	if [ "${privileged}" -eq 1 ] && [ "${unshare_netns}" -eq 0 ] && [ -e "/sys/fs/selinux" ]; then
 		result_command="${result_command}
 			--volume /sys/fs/selinux"
 	fi
@@ -876,13 +933,18 @@ generate_create_command()
 	# This works around this using an unnamed volume so that this path will be
 	# mounted with a normal non-overlay FS, allowing ACLs and preventing errors.
 	#
-	# This work around works in conjunction with distrobox-init's package manager
+	# This work around works in conjunction with distrobox-isolated-init's package manager
 	# setups.
 	# So that we can use pre/post hooks for package managers to present to the
 	# systemd install script a blank path to work with, and mount the host's
 	# journal path afterwards.
-	result_command="${result_command}
+	if [ "${unshare_journal}" -eq 0 ]; then
+		result_command="${result_command}
 			--volume /var/log/journal"
+	else
+		result_command="${result_command}
+			--mount type=tmpfs,target=/var/log/journal"
+	fi
 
 	# In some systems, for example using sysvinit, /dev/shm is a symlink
 	# to /run/shm, instead of the other way around.
@@ -896,7 +958,7 @@ generate_create_command()
 	# Ensure that both all container managers (not only podman) support forwarding of RedHat subscription-manager
 	# This is needed in order to have a working subscription forwarded into the container,
 	# this will ensure that rhel-9-for-x86_64-appstream-rpms and rhel-9-for-x86_64-baseos-rpms repos
-	# will be available in the container, so that distrobox-init will be able to
+	# will be available in the container, so that distrobox-isolated-init will be able to
 	# install properly all the dependencies like mesa drivers.
 	#
 	# /run/secrets is a standard location for RHEL containers, that is being pointed by
@@ -930,10 +992,18 @@ generate_create_command()
 				exit 1
 			fi
 		fi
-		result_command="${result_command}
-			--env \"HOME=/home/${container_user_name}\"
-			--volume \"${container_user_custom_home}/.home\":\"/home/${container_user_name}\":rslave
-			--volume \"${container_user_custom_home}\":\"${container_user_custom_home}\":rslave"
+
+		if [ "${home_overlay_opts}" != "-" ]; then
+			result_command="${result_command}
+				--env \"HOME=/home/${container_user_name}\"
+				--volume \"${container_user_custom_home}/.home\":\"/home/${container_user_name}\":\"O${home_overlay_opts}\"
+				--volume \"${container_user_custom_home}\":\"${container_user_custom_home}\":\"O${home_overlay_opts}\""
+		else
+			result_command="${result_command}
+				--env \"HOME=/home/${container_user_name}\"
+				--volume \"${container_user_custom_home}/.home\":\"/home/${container_user_name}\":rslave
+				--volume \"${container_user_custom_home}\":\"${container_user_custom_home}\":rslave"
+		fi
 	fi
 
 	# Mount also the /var/home dir on ostree based systems
@@ -1027,9 +1097,9 @@ generate_create_command()
 	result_command="${result_command}
 		${container_manager_additional_flags}"
 
-	# Now execute the entrypoint, refer to `distrobox-init -h` for instructions
+	# Now execute the entrypoint, refer to `distrobox-isolated-init -h` for instructions
 	#
-	# Be aware that entrypoint corresponds to distrobox-init, the copying of it
+	# Be aware that entrypoint corresponds to distrobox-isolated-init, the copying of it
 	# inside the container is moved to distrobox-enter, in the start phase.
 	# This is done to make init, export and host-exec location independent from
 	# the host, and easier to upgrade.
@@ -1048,9 +1118,15 @@ generate_create_command()
 		--nvidia \"${nvidia}\"
 		--pre-init-hooks \"${container_pre_init_hook}\"
 		--additional-packages \"${container_additional_packages}\"
-		-- '${container_init_hook}'
 	"
-	# use container_user_custom_home if defined, else fallback to normal home.
+
+	if [ "${privileged}" -eq 1 ]; then
+	    result_command="${result_command}
+			--privileged"
+	fi
+
+	result_command="${result_command}
+	    -- '${container_init_hook}'"
 
 	# Return generated command.
 	printf "%s" "${result_command}"
